### ISSUE TITLE
 TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by netzkind** [CacheControl/hippie-swagger#19]
hippie-swagger chokes when using recursive or circular references.

Versions:
node 7.4.0 or 6.9.2
hippie-swagger 2.1.0
ajv 4.11.2
json-stable-stringify 1.0.1

definition:
```
swagger: '2.0'
info:
  description: navigation

basePath: /
produces:
  - application/json
paths:
  /v1/Navigation/getNavigationByIso/de-DE:
    get:
      description: gets the navigation tree by iso code
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/navigation'

definitions:
  navigation:
    description: complete navigation tree
    type: object
    properties:
      nodes:
        type: array
        items:
          $ref: '#/definitions/navigationNode'
    required:
      - nodes

  navigationNode:
    description: a single navigation node including its children
    type: object
    properties:
      subnodes:
        description: zero or more child-nodes of this navigation node
        type: array
        items:
          $ref: '#/definitions/navigationNode'
    required:
      - subnodes
```

test-code:
```
'use strict';

const SwaggerParser = require('swagger-parser');
const parser = new SwaggerParser();
const hippie = require('hippie-swagger');
const app = require('../../server/server.js');
let dereferencedSwagger;
const swaggerFile = 'swagger/navigation.yaml';

describe('Test of Navigation.yaml', function () {
    before(function (done) {
        parser.dereference(swaggerFile, function (err, api) {
            if (err) return done(err);
            dereferencedSwagger = api;
            done();
        });
    });

    describe('get HTTP-Statuscode 200', function () {
        it('works when the request matches the swagger file', function (done) {
            hippie(app, dereferencedSwagger)
                .get('/v1/Navigation/getNavigationByIso/de-DE')
                .expectStatus(200)
                .end(done);
        })
    });
});
```

result:
```
1) Test of Navigation.yaml get HTTP-Statuscode 200 works when the request matches the swagger file:
     TypeError: Converting circular structure to JSON
      at stringify (node_modules/json-stable-stringify/index.js:49:23)
      at stringify (node_modules/json-stable-stringify/index.js:57:29)
      at stringify (node_modules/json-stable-stringify/index.js:57:29)
      at stringify (node_modules/json-stable-stringify/index.js:57:29)
      at stringify (node_modules/json-stable-stringify/index.js:57:29)
      at stringify (node_modules/json-stable-stringify/index.js:57:29)
      at stringify (node_modules/json-stable-stringify/index.js:57:29)
      at module.exports (node_modules/json-stable-stringify/index.js:70:7)
      at _addSchema (node_modules/hippie-swagger/node_modules/ajv/lib/ajv.js:276:19)
      at Ajv.validate (node_modules/hippie-swagger/node_modules/ajv/lib/ajv.js:94:23)
      at validateBody (node_modules/hippie-swagger/lib/response.js:20:14)
      at Client.response (node_modules/hippie-swagger/lib/response.js:45:5)
      at verify (node_modules/hippie/lib/hippie/client.js:476:5)
      at statusCode (node_modules/hippie/lib/hippie/expect.js:23:5)
      at verify (node_modules/hippie/lib/hippie/client.js:476:5)
      at Client.verify (node_modules/hippie/lib/hippie/client.js:477:5)
      at node_modules/hippie/lib/hippie/client.js:437:12
      at Client.exports.json [as parse] (node_modules/hippie/lib/hippie/parsers.js:21:3)
      at Request._callback (node_modules/hippie/lib/hippie/client.js:435:10)
      at Request.self.callback (node_modules/hippie/node_modules/request/request.js:187:22)
      at Request.<anonymous> (node_modules/hippie/node_modules/request/request.js:1044:10)
      at IncomingMessage.<anonymous> (node_modules/hippie/node_modules/request/request.js:965:12)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

Documentation for SwaggerParser suggests to use "bundle" instead of "dereference", but hippie-swagger will not work if/when references are not fully resolved (not visible in the example above, but then hippie-swagger will not recognize path-params when using references for them).

**Comment by CacheControl** [comment]
I was able to reproduce the issue using the snippets you provided - thanks! However, after doing some research, this issue appears in the json-schema dependency of hippie-swagger called `ajv`, which in turn has a dependency issue in `json-stable-stringify`.  

You can read what the author of `ajv` has to say about the problem [here](https://github.com/epoberezkin/ajv/issues/461), but the TL;DR seems to be that the practice of using self-referencing schemas should be avoided.  `ajv` is far and away the best json-schema package around, and I trust the author's opinion.
