### ISSUE TITLE
Swagger path not recognized

### ISSUE THREAD

**Issue by lcofre** [CacheControl/hippie-swagger#32]
Hi!

When processing an example swagger definition hippie-swagger complains of an undefined path that is defined:

```
'use strict'

var SwaggerParser = require('swagger-parser')
var parser = new SwaggerParser()
var hippie = require('hippie-swagger')
var expect = require('chai').expect
var path = require('path')
var dereferencedSwagger

describe('Example of', function () {
  before(function (done) {
    parser.dereference('https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v2.0/json/petstore.json', function (err, api) {
      if (err) return done(err)
      dereferencedSwagger = api
      done()
    })
  })

  describe('correct usage', function () {
    it('should allow to post to /pets', function (done) {
      hippie(dereferencedSwagger)
      .json()
      .post('/pets')
      .expectStatus(200)
      .end(done)
    })
  })
})
```

The answer I receive is:
```
$ mocha index.js


  Example of
    correct usage
      1) should allow to post to /pets


  0 passing (225ms)
  1 failing

  1) Example of correct usage should allow to post to /pets:
     Error: Swagger spec does not define path: /pets
      at Client.middleware (node_modules/hippie-swagger/lib/middleware.js:15:13)
      at next (node_modules/hippie/lib/hippie/client.js:456:5)
      at Client.setup (node_modules/hippie/lib/hippie/client.js:457:5)
      at Client.prepare (node_modules/hippie/lib/hippie/client.js:364:17)
      at Client.end (node_modules/hippie/lib/hippie/client.js:382:24)
      at Context.<anonymous> (index.js:32:8)
```

By the way, thanks for this awesome project!

**Comment by CacheControl** [comment]
@lcofre I don't have time to investigate this right now, but looking at that example swagger file, I notice it defines a `basePath` of `/v1` -- have you tried changing that test to post to `/v1/pets`?

**Comment by lcofre** [comment]
Now the message changed slightly:
```
  1) Example of correct usage should allow to post to /pets:
     Error: Invalid URI "/v2/pet"
      at Request.init (node_modules/request/request.js:275:31)
      at new Request (node_modules/request/request.js:129:8)
      at request (node_modules/request/index.js:55:10)
      at Client.request (node_modules/hippie/lib/hippie/client.js:433:3)
      at next (node_modules/hippie/lib/hippie/client.js:455:27)
      at Client.middleware (node_modules/hippie-swagger/lib/middleware.js:57:3)
      at next (node_modules/hippie/lib/hippie/client.js:456:5)
      at Client.setup (node_modules/hippie/lib/hippie/client.js:457:5)
      at node_modules/hippie/lib/hippie/client.js:370:10
      at Client.exports.json [as serialize] (node_modules/hippie/lib/hippie/serializers.js:28:3)
      at Client.prepare (node_modules/hippie/lib/hippie/client.js:367:8)
      at Client.end (node_modules/hippie/lib/hippie/client.js:382:24)
      at Context.<anonymous> (index.js:32:8)
```

(I changed the example API because v1 is not up anymore)
```
// ...
    parser.dereference('http://petstore.swagger.io/v2/swagger.json', function (err, api) {
      if (err) return done(err)
// ...
```
and the test
```
      // ...
      hippie(dereferencedSwagger)
      .json()
      .send({name:"", photoUrls:[]})
      .post('/v2/pet')
      .expectStatus(200)
      .end(done)
      // ...
```

Thanks for the time spent even when you are busy!

**Comment by CacheControl** [comment]
@lcofre Oops, the other I missed that you were forgetting the first argument to hippie-swagger() - your app!  Please [see the example](https://github.com/CacheControl/hippie-swagger/blob/master/example/index.js#L32) for proper usage

**Comment by lcofre** [comment]
Sorry! I supposed that with no app, it'll try to test the "host" in the swagger definition or the server where the definition is hosted in. Is this not true?

Or in other words, can I only test NodeJS apps?

Thanks very much for your time!

**Comment by CacheControl** [comment]
@lcofre ah!  yes you can absolutely test non-node applications this way.  You just have to include the full uri in the request.  This isn't well documented and I'll make a note to build a full fledged example for this use case. 

Here's a working snippet that I tested locally:

```js
'use strict'

var SwaggerParser = require('swagger-parser')
var parser = new SwaggerParser()
var hippie = require('./index')
var expect = require('chai').expect
var path = require('path')
var dereferencedSwagger

describe('Example of', function () {
  before(function (done) {
    parser.dereference('https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v2.0/json/petstore.json', function (err, api) {
      if (err) return done(err)
      dereferencedSwagger = api
      done()
    })
  })

  describe('correct usage', function () {
    it('should allow to post to /pets', function (done) {
      hippie(dereferencedSwagger)
      .json()
      .post('http://localhost:3000/v1/pets')   // fully qualified url
      .expectStatus(201)
      .end(done)
    })
  })
})
```

And the example server (can be run by any language / backend):
```js
var http = require('http');

//create a server object:
http.createServer(function (req, res) {
  res.statusCode = 201
  res.write(JSON.stringify({}));
  res.end();
}).listen(3000);
```
